name: flair-mongo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.7
  - python-dateutil
  - pytorch
  - gensim
  - pytest
  - tqdm
  - matplotlib
  - mpld3
  - scikit-learn
  - deprecated
  - regex
  - tabulate
  - urllib3
  - sqlitedict
  - hyperopt
  - langdetect
  - numpy
  - pandas
  - ipython
  - jupyter
  - nltk
  - pymongo
  - pytorch
  - torchvision
  - cudatoolkit
  - pip:
    - segtok
    - bpemb
    - pillow==6.1
    - tiny-tokenizer
    - transformers
